name: Porfolio Deployment

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: cURL AxiosJS
  # You may pin to the exact commit or the version.
  # uses: indiesdev/curl@5f733a4ab67799ec174b9b9b3f8d78100ae084e8
      uses: indiesdev/curl@v1.1
      with:
        # The target url
        url: https://windmill.koltserver.net/api/w/app-pipelines/jobs/run/f/f/cicd/update_repo
        # The request method, basically one of GET, POST, PUT, PATCH
        # List of status codes to be accepted, else it is considerred to be failed
        # Headers object
        method: POST
        headers: '{"Content-Type": "application/json","Authorization": "Bearer 9zS3g6BsIWXGLtAV3TjH1McnRxuBu6"}'
        # Params object
        # Body object
        body: '{"Image tag": "","Image name": "portfolio","Repository": "https://github.com/YD-S/Portfolio.git","Portainer Webhook": "https://portainer.koltserver.net/api/stacks/webhooks/29da2db5-3bb1-4f8e-925a-9524f327ba65"}'
              
